/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'heijmans' at '1/17/17 9:32 AM' with Gradle 2.14.1
 *
 * @author heijmans, @date 1/17/17 9:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
